Minor change- > improve _pause() function to accept both timeout and keypress, so during setup, we can skip sleep function by pressing enter.

diff --git a/maxisetup b/maxisetup
--- a/maxisetup
+++ b/maxisetup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 # Author: Arafat Ali Email: arafat@sofibox.com
-# Version 0.3.3.8-beta
+# Version 0.3.3.9-beta
 # This is an initial server hardening script for general server using CentOS and Debian.
 # Compatible 100% with Directadmin. Supported OS: CentOS + Debian (Planned on FreeBSD)
 # Read the code to know what the scripts offer.
@@ -68,15 +68,24 @@ function get_linux_os() {
 
 }
 
-# Pause terminal without exit
+# Pause terminal, press enter or wait within <duration_in_seconds> to continue the next command
+# eg: _pause (no timeout. need to press enter to continue)
+# eg: _pause 10 (wait 10 seconds or press enter to continue)
 function _pause() {
-  read -r -s -n 1 -p "[${SCRIPT_NAME}]: Press any key to continue . . ." 2>&1 | tee -a "${REPORT_FILE}"
+  local duration=$1
+  # If argument is not an integer, we disable read timeout
+  if [[ ${duration} =~ ^[0-9]+$ ]]; then
+    read -t "${duration}" -r -s -n 1 -p "[${SCRIPT_NAME}]: Press any key or wait ${duration} second(s) to continue or press (Ctrl+c) to cancel ..." 2>&1 | tee -a "${REPORT_FILE}"
+  else
+    read -r -s -n 1 -p "[${SCRIPT_NAME}]: Press any key to continue or press (Ctrl+c) to cancel ..." 2>&1 | tee -a "${REPORT_FILE}"
+  fi
   echo ""
+
 }
 # Pause terminal with exit return code
 # Use _ symbol to not override exit function
 function _exit() {
-  read -r -s -n 1 -p "[${SCRIPT_NAME}]: Press any key to exit . . ." 2>&1 | tee -a "${REPORT_FILE}"
+  read -r -s -n 1 -p "[${SCRIPT_NAME}]: Press any key to exit ..." 2>&1 | tee -a "${REPORT_FILE}"
   echo ""
   exit "$1"
 }
@@ -131,7 +140,7 @@ function da_api_admin() {
   admin_ori_list="/usr/local/directadmin/scripts/setup.txt"
   action="$1"
 
-  if [[ "${SETUP_DA_HOST_SSL}" == "yes" && -f "${CONF_PATH}/enable_da_ssl_executed" ]]; then
+  if [[ "${SETUP_DA_HOST_SSL}" == "yes" && -f "${CONF_PATH}/configure_da_ssl_executed" ]]; then
     ssl="https"
   else
     ssl="http"
@@ -1129,9 +1138,9 @@ configure_csf() {
         echo "-----------------" 2>&1 | tee -a "${REPORT_FILE}"
         grep ^TCP_IN /etc/csf/csf.conf 2>&1 | tee -a "${REPORT_FILE}"
         echo "" 2>&1 | tee -a "${REPORT_FILE}"
-        echo "If you do NOT see the port listed, press ctrl-c to immediately abort the script." 2>&1 | tee -a "${REPORT_FILE}"
+        echo "If you do NOT see the port listed, press ctrl-c to immediately abort the script (you can add port missing port in maxi.env), then re-run this setup" 2>&1 | tee -a "${REPORT_FILE}"
         echo "If you DO, the port correctly added, press enter to continue" 2>&1 | tee -a "${REPORT_FILE}"
-        _pause
+        _pause 60
         if [ "${DISTRO_ID}" == "centos" ]; then
           echo "[${SCRIPT_NAME}]: Disabling built-in firewall (firewalld) in CentOS ..." 2>&1 | tee -a "${REPORT_FILE}"
           systemctl disable firewalld 2>&1 | tee -a "${REPORT_FILE}"
@@ -1246,8 +1255,7 @@ function install_da() {
     chmod 755 setup.sh
     echo "[${SCRIPT_NAME}]: Setup will install Directadmin within 30 seconds. It would take a long time, so please be patient" 2>&1 | tee -a "${REPORT_FILE}"
     echo "[${SCRIPT_NAME}]: If you don't want to install Directadmin now, press (ctrl+C) to exit and then you can re-run this script to resume at this stage" 2>&1 | tee -a "${REPORT_FILE}"
-    echo "[${SCRIPT_NAME}]: Setup will continue within 30 seconds press (ctrl+c) to exit..." 2>&1 | tee -a "${REPORT_FILE}"
-    sleep 30
+    _pause 30
     echo "[${SCRIPT_NAME}]: Installing Directadmin on ${BOX_HOSTNAME_FQDN} using ${DA_INSTALL_TYPE} mode ... " 2>&1 | tee -a "${REPORT_FILE}"
     if [[ "${DA_INSTALL_TYPE}" == "CUSTOM" || "${DA_INSTALL_TYPE}" == "ORI" ]]; then
       # custom and ori depends on the options.conf (this won't ask question)
@@ -1477,13 +1485,13 @@ function install_da_post() {
 }
 
 # This is the pre-requirement before getting ssl
-function enable_da_ssl_pre() {
+function configure_da_ssl_pre() {
   if [ ! -f "${CONF_PATH}/${FUNCNAME[0]}_executed" ]; then
     echo "[${SCRIPT_NAME}]: Executing ${FUNCNAME[0]} ..." 2>&1 | tee -a "${REPORT_FILE}"
     echo "[${SCRIPT_NAME}]: Creating reboot flag to restart system before requesting SSL certificate for Directadmin ..." 2>&1 | tee -a "${REPORT_FILE}"
     cat /dev/null >/var/run/reboot-required
     echo "[${SCRIPT_NAME}]: Warning, system will reboot and you can run this script again to continue setup" 2>&1 | tee -a "${REPORT_FILE}"
-    _pause
+    _pause 10
     check_finish_reboot "${FUNCNAME[0]}"
   else
     echo "[${SCRIPT_NAME}]: [Skipped]: ${FUNCNAME[0]} has ran before" 2>&1 | tee -a "${REPORT_FILE}"
@@ -1491,7 +1499,7 @@ function enable_da_ssl_pre() {
   fi
 }
 
-function enable_da_ssl() {
+function configure_da_ssl() {
   # Request SSL failed due to DAD (until server restart)
   # Interesting answer: https://serverfault.com/questions/602700/debian-ipv6-is-not-asssigned-to-interface
   # Nice reading: https://www.agwa.name/blog/post/beware_the_ipv6_dad_race_condition
@@ -2478,7 +2486,7 @@ function configure_maxiaide() {
 
 function configure_maxicata() {
   # Debug
-  rm -f "${CONF_PATH}/configure_maxicata_executed"
+  # rm -f "${CONF_PATH}/configure_maxicata_executed"
   if [ ! -f "${CONF_PATH}/${FUNCNAME[0]}_executed" ]; then
     echo "[${SCRIPT_NAME}]: Executing ${FUNCNAME[0]} ..." 2>&1 | tee -a "${REPORT_FILE}"
     local latest_suricata_version suricata_service is_masked suricata_select_version suricata_conf maxicata_bin maxirbl_bin
@@ -2644,7 +2652,6 @@ function configure_maxicata() {
     #  echo "[${SCRIPT_NAME}]: Warning, suricata process is not active [unknown reason]. Please inspect log file to understand the reason" 2>&1 | tee -a "${REPORT_FILE}"
     #  _exit 1
     #fi
-
 
     maxicata_bin="/usr/local/maxicode/maxicata/maxicata"
 
@@ -3038,7 +3045,7 @@ fi
 if compgen -G "${CONF_PATH}/*_executed" >/dev/null; then
   echo "[${SCRIPT_NAME} | ${DATE_TIME_NOW}]: Resuming from previous installation ..." 2>&1 | tee -a "${REPORT_FILE}"
   START_OR_RESUME="Resuming"
-  _pause
+  _pause 10
 else
   START_OR_RESUME="Starting"
 fi
@@ -3104,12 +3111,12 @@ configure_maxicata
 # If I don't restart, I won't be able to request cert and letsencrypt will complain about firewall.
 #configure_logs
 if [ "${INSTALL_TYPE}" == "DIRECTADMIN" ]; then
-  # Must run this functions (enable_da_ssl) after running CSF because we need to make sure all appropriate ports are opened to request certs
-  # Warning do not overused enable_da_ssl function because when requesting the same cert for the same domain 7 times for a week, you will get blocked.
-  enable_da_ssl_pre
-  exit 1
-  enable_da_ssl #OK
+  # Must run this functions (configure_da_ssl) after running CSF because we need to make sure all appropriate ports are opened to request certs
+  # Warning do not overused configure_da_ssl function because when requesting the same cert for the same domain 7 times for a week, you will get blocked.
+  configure_da_ssl_pre
   #exit 1
+  configure_da_ssl #OK
+  exit 1
   configure_da_sql #OK
   #exit 1
   configure_da_mail #OK but need to test again
@@ -3148,6 +3155,6 @@ echo ""
 script_time
 echo "========== Installation Completed ==========" 2>&1 | tee -a "${REPORT_FILE}"
 echo ""
-echo "[${SCRIPT_NAME}]: Destroying ${ENVIRONMENT_FILE} file in 30 seconds (ctrl+c to cancel) ..." 2>&1 | tee -a "${REPORT_FILE}"
-sleep 30
+echo "[${SCRIPT_NAME}]: Destroying ${ENVIRONMENT_FILE} file in 30 seconds ..." 2>&1 | tee -a "${REPORT_FILE}"
+_pause 30
 shred -uvz "${ENVIRONMENT_FILE}"
