Fixed writing new email aliases duplication Fixed mail command not found Fixed .htaccess was not copied from webapps Added SMTP configuration with mail test Removed ./build bubblewrap just use ./build jailshell Fixed mysql command not found Added maxiclam installation. This CLI can manage both maldet and clamAV
Updated maxinet.conf.sample

New variables from maxinet.con.sample:

# This is for system mail (use for notification, or reports)
# Email username
C_SMTP_SYSTEM_MAIL_USER="mailuser"
# Mail domain
C_SMTP_SYSTEM_MAIL_DOMAIN="gmail.com"
# For gmail use app password
C_SMTP_SYSTEM_MAIL_PASSWORD="mpsssepsousda2xx"
# The smtp domain
C_SMTP_SYSTEM_MAIL_SMTP_URL="smtp.gmail.com"
# The authentication port
C_SMTP_SYSTEM_MAIL_PORT="587"
# Format email(<name_description>)
C_SMTP_SYSTEM_MAIL_FROM="arafatx@gmail.com(Arafat)"

diff --git a/maxinet b/maxinet
--- a/maxinet
+++ b/maxinet
@@ -5,7 +5,7 @@
 # remote OS tested: debian 11
 _APP_SPECIFIC_NAME="Maxinet"
 # Note that some minor versions are not published
-_APP_VERSION="0.9.2"
+_APP_VERSION="0.9.4"
 _APP_STATUS="alpha"
 _APP_VERSION_STATUS="${_APP_VERSION}-${_APP_STATUS}"
 
@@ -11284,7 +11284,7 @@ install_da_post() {
   fi
   [[ "${SKIP_RUN}" == "true" ]] && return 0
   if [[ ! -f "${CONF_PATH}/${func_name}_executed" && "${FUNCTION_RUN}" == "true" ]]; then
-    local da_conf da_sql_type da_sql_version da_install_log da_bin da_cb_bin da_script_path
+    local da_conf da_sql_type da_sql_version da_install_log da_bin da_cb_bin da_script_path grep_count
     da_conf="/usr/local/directadmin/conf/directadmin.conf"
     da_bin="/usr/local/directadmin/directadmin"
     da_cb_bin="/usr/local/directadmin/custombuild/build"
@@ -11297,16 +11297,96 @@ install_da_post() {
 
     echo ""
 
-    # I add this here because this needs exim to be installed first
-    _echo "$(msg cyan)Writing new email aliases at /etc/aliases ...$(msg end)" --name
-    #Root email will use this one
-    {
+    # I add this here because this needs exim to be installed first after da has been installed
+    grep_count=$(grep -ic "diradmin: :blackhole:" /etc/aliases)
+    if [ "${grep_count}" -eq 0 ]; then
+      _echo "$(msg cyan)Writing new email aliases 'diradmin: :blackhole:' at /etc/aliases ...$(msg end)" --name
       echo "diradmin: :blackhole:" >>/etc/aliases
+    else
+      _echo "$(msg yellow)[Skipped]: The diradmin: :blackhole: value was previously set in /etc/aliases!$(msg end)" --name
+    fi
+
+    echo ""
+
+    grep_count=$(grep -ic "root:${C_ROOT_EMAIL}" /etc/aliases)
+    if [ "${grep_count}" -eq 0 ]; then
+      _echo "$(msg cyan)Writing new email aliases root:${C_ROOT_EMAIL} at /etc/aliases ...$(msg end)" --name
+      #Root email will use this one
       echo "root:${C_ROOT_EMAIL}" >>/etc/aliases
-    } >>/etc/aliases
+    else
+      _echo "$(msg yellow)[Skipped]: The root:${C_ROOT_EMAIL} value was previously set in /etc/aliases!$(msg end)" --name
+    fi
+
     get_status_message $?
     _echo "$(msg cyan)Running newaliases command ... $(msg end)" --name
     newaliases
+    get_status_message "$?"
+    echo ""
+
+    # This fixed the binary or symlink mail did not create after s-nail being installed
+    _echo "$(msg cyan)Checking mail command ...$(msg end)" --name
+    if ! command -v mail &>/dev/null; then
+      _echo "$(msg yellow)Warning, mail command is not found. Checking s-nail command ...$(msg end)" --name
+      if command -v s-nail &>/dev/null; then
+        _echo "$(msg cyan)s-nail command is found! Creating a mail symlink to s-nail ...$(msg end)" --name
+        ln -s "$(command -v s-nail)" /usr/bin/mail
+        get_status_message "$?"
+      else
+        _echo "$(msg yellow)Error, required mail command/binary. You may need to manually install this mail package!$(msg end)" --name
+        _exit 147
+      fi
+    fi
+    echo ""
+    # Now we can setup SMTP using s-nail
+    {
+      _echo "$(msg cyan)Creating mail SMTP file at /root/.mailrc ...$(msg end)" --name
+      echo "# ==============================================="
+      echo "# This configuration file was generated by ${SCRIPT_NAME}"
+      echo "# Author: ${C_ADMIN_NAME} | Email: ${C_ADMIN_EMAIL} | Web: ${C_BOX_DOMAIN}"
+      echo "# ==============================================="
+
+      echo "# This configuration is taken from https://manpages.debian.org/stretch/s-nail/s-nail.1.en.html"
+      echo ""
+      echo "# To test mail configuration, use the following syntax to send mail:"
+      echo "# echo \"Test\" | mail -s \"My test...\" address@whatever.com"
+      echo ""
+      echo "# This set v15.0 compatibility mode"
+      echo "set v15-compat"
+      echo ""
+      echo "# See the whole process, especially for troubleshooting:"
+      echo "set verbose"
+      echo ""
+      echo "# Essential setting: select allowed character sets"
+      echo "set sendcharsets=utf-8,iso-8859-1"
+      echo "# when replying to a message, first try to use the same encoding that the original poster used herself!"
+      echo "set reply-in-same-charset"
+      echo ""
+      echo "# Default directory where we act in (relative to \$HOME)"
+      echo "set folder=mail"
+      echo ""
+      echo "# Request strict TLS transport layer security checks"
+      echo "set tls-verify=strict"
+      echo "set tls-ca-file=/etc/ssl/certs/ca-certificates.crt"
+      echo "set tls-ca-no-defaults"
+      echo "set smtp-use-starttls"
+      echo "set smtp-auth=login"
+      echo ""
+      echo "# When sending a message wait until the MTA (including the builtin SMTP one) exits before accepting further commands."
+      echo "# Only with this variable set errors reported by the MTA will be recognizable!"
+      echo "# If the MTA returns a non-zero exit status, the exit status of s-nail will also be non-zero"
+      echo "set sendwait"
+      echo ""
+      echo "# set from=\"Your Name <youremail@domain>\""
+      echo "set from=\"${C_SMTP_SYSTEM_MAIL_FROM}\""
+      echo "Put authentication information here from config file"
+      echo "set mta=smtp://${C_SMTP_SYSTEM_MAIL_USER}:${C_SMTP_SYSTEM_MAIL_PASSWORD}@${C_SMTP_SYSTEM_MAIL_SMTP_URL}:${C_SMTP_SYSTEM_MAIL_PORT}"
+
+    } >/root/.mailrc
+    get_status_message "$?"
+
+    echo ""
+    _echo "$(msg cyan)Correcting permission file of /root/.mailrc ...$(msg end)" --name
+    chmod 600 /root/.mailrc
     get_status_message "$?"
     echo ""
 
@@ -11322,6 +11402,12 @@ install_da_post() {
       systemctl restart postfix
       echo ""
     fi
+
+    _echo "$(msg cyan)Testing sending mail...$(msg end)" --name
+    echo "If you can read this, that means the SMTP mail for ${C_BOX_HOSTNAME_FQHN} has been successfully configured" | mail -s "SMTP mail testing from ${C_BOX_HOSTNAME_FQHN}" ${C_SMTP_SYSTEM_MAIL_USER}@${C_SMTP_SYSTEM_MAIL_DOMAIN}
+    get_status_message "$?"
+
+    echo ""
     # Rebuilding DA packages to fix some issues .
     _echo "$(msg cyan)Updating directadmin custombuild to the new version...$(msg end)" --name
     ${da_cb_bin} update
@@ -11330,8 +11416,10 @@ install_da_post() {
     if [ "${C_DA_CB_INSTALL_SANDBOX}" == "yes" ]; then
       # Installing bubble wrap (jailshell)
       _echo "$(msg cyan)Installing bubble wrap (jailshell) ...$(msg end)" --name
-      ${da_cb_bin} bubblewrap
+      # The command bubblewrap is not required anymore (jailshell will take care):
+      # ${da_cb_bin} bubblewrap https://forum.directadmin.com/threads/directadmin-v1-645-has-been-released.67373/post-354947
       ${da_cb_bin} jailshell
+      get_status_message "$?"
       echo ""
     fi
 
@@ -12711,8 +12799,12 @@ configure_da_sql() {
     echo ""
     _echo "$(msg cyan)Checking whether mysql is installed (binary file exist) ...$(msg end)" --name
     if ! command -v mysql &>/dev/null; then
-      _echo "$(msg red)Error, mysql binary is not found. Please inspect why and re-run this script to continue$(msg end)" --name
-      _exit 147
+      _echo "$(msg yellow)Error, mysql binary is not found. Creating mysql symlink ...$(msg end)" --name
+      # This error has been fixed as I reported https://forum.directadmin.com/threads/directadmin-v1-645-has-been-released.67373/page-2#post-354952
+      # and here: https://forum.directadmin.com/threads/da-v-1-645-mysql-and-mail-binary-are-missing-on-clean-install-debian-11.67378/#post-354953
+      # but in case mysql binary is not found again, we can just create symlink
+      ln -s /usr/local/bin/mariadb /usr/local/bin/mysql
+      get_status_message "$?"
     fi
     echo ""
     _echo "$(msg cyan)Checking which mysql authentication to use ...$(msg end)" --name
@@ -13798,7 +13890,8 @@ configure_web_apps() {
     # get_latest_code
 
     _echo "$(msg cyan)Copying custom webapps from storage into /var/www/html ...$(msg end)" --name
-    cp -r ${LATEST_OS_CODE_PATH}/var/www/html/* /var/www/html/
+    mkdir -p /var/www/html
+    cp -ra "${LATEST_OS_CODE_PATH}"/var/www/html/. /var/www/html/
     get_status_message $?
     echo ""
 
@@ -17331,6 +17424,50 @@ configure_maxirbl() {
   fi
 }
 
+configure_maxiclam() {
+  local run_mode func_name
+  run_mode="$1"
+  extra_option="$2"
+  func_name="${FUNCNAME[0]}"
+  if [[ "${extra_option}" == "--silent-if-executed" ]]; then
+    start_execute_options "${run_mode}" "${func_name}" &>/dev/null
+  else
+    start_execute_options "${run_mode}" "${func_name}"
+  fi
+  [[ "${SKIP_RUN}" == "true" ]] && return 0
+  if [[ ! -f "${CONF_PATH}/${func_name}_executed" && "${FUNCTION_RUN}" == "true" ]]; then
+    local maxiclam_bin
+    maxiclam_bin="/usr/local/maxicode/maxiclam/maxiclam"
+    _echo "$(msg cyan)Removing previous blcheck symlink shortcut in /usr/local/bin ...$(msg end)" --name
+    rm -f /usr/local/bin/maxiclam
+    if [ -f ${maxiclam_bin} ]; then
+      _echo "$(msg cyan)Setting ${maxiclam_bin} script to have executable permission ...$(msg end)" --name
+      chmod +x "${maxiclam_bin}"
+      _echo "$(msg cyan)Creating symlink for ${maxiclam_bin} ...$(msg end)" --name
+      ln -s "${maxiclam_bin}" /usr/local/bin
+      echo ""
+      _echo "$(msg cyan)Running maxiclam -V ...$(msg end)" --name
+      maxiclam -V
+      get_status_message "$?"
+      echo ""
+    else
+      _echo "$(msg red)Warning, maxiclam binary doesn't exist inside /usr/local/maxicode ...$(msg end)" --name
+      _exit 147
+    fi
+    echo ""
+    check_finish_reboot "${func_name}"
+  else
+    _echo "$(msg yellow)[Skipped by system]: $(msg magenta)${func_name}$(msg end) $(msg yellow)with current option ${run_mode} has ran before $(msg end)" --name
+    _echo "$(msg yellow)=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=$(msg end)" --plain
+  fi
+
+  if [[ "${extra_option}" == "--silent-if-executed" ]]; then
+    end_execute_options "${run_mode}" "${func_name}" &>/dev/null
+  else
+    end_execute_options "${run_mode}" "${func_name}"
+  fi
+}
+
 configure_maxiwall() {
   #Fixed bug from this helpful solution:
   #https://forum.suricata.io/t/latest-suricata-6-0-2-with-rustc-has-trouble-installing-with-error-could-not-compile-lexical-core/1461/3
@@ -20340,8 +20477,9 @@ setup() {
         configure_maxicloud --run
         configure_maxipass --run
         configure_maxidb --run
-        configure_maxify --skip # (skipped deprecated)
-        configure_logs --skip   #-- skip temporarily
+        configure_maxify --skip  # (skipped deprecated)
+        configure_maxiclam --run #
+        configure_logs --skip    #-- skip temporarily
         configure_maxicron --run
         # Still need to add more based on lynis suggestion
         harden_with_lynis --run
