Improved ssh_login code Added documentation in the terminal to resume remote installation (in the case setup needs to restart remotely). This will display when SSH is terminated. Improved check_finish_reboot function Added the ability to detect if OS is encrypted. Hence, the variable DISK_ENCRYPTION used to specify OS encryption status manually is now deprecated. Renamed variable disk_uuid to local disk_uuid_boot because this uuid is only for boot partition Extra ports specification config for variable CSF_EXTRA_ALLOW_PORTS now doesn't need to specify comma at the beginning. Added new variable CSF_DENY_IP_LIMIT to increase DENY_IP_LIMIT from 200 (default) to any values. This one was missing feature. Added speedtest.net installation in post_setup() Added the ability to automatically unlock LUKS encryption remotely and run maxisetup automatically. Other changes ... especially in maxida, maxiwall, websetup .. other extra things

diff --git a/maxisetup b/maxisetup
--- a/maxisetup
+++ b/maxisetup
@@ -3,7 +3,7 @@
 # Author: Arafat Ali | Email: webmaster@sofibox.com
 APP_SPECIFIC_NAME="Maxisetup"
 APP_STATUS="beta"
-APP_VERSION="0.4.3.1-${APP_STATUS}"
+APP_VERSION="0.4.3.3-${APP_STATUS}"
 # This is an initial server hardening script for CentOS and Debian.
 # Compatible 100% with Directadmin. Supported OS: CentOS + Debian (Planned on FreeBSD)
 # You can choose to install as the other stack server such as LEMP, (TODO) Laravel and more defined in config file
@@ -14,14 +14,19 @@ APP_VERSION="0.4.3.1-${APP_STATUS}"
 # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~="
 # Run with log output: ./maxisetup --setup 2>&1 | tee maxisetup.log
 # TOP TO DO LIST:
-# TODO: Enable DNSSEC https://help.directadmin.com/item.php?id=651
+# TODO: Enable DNSSEC https://help.directadmin.com/item.php?id=651 (also check mail configuration to support new ipv6)
 # TODO: enable --dry-run (that will simulate testing for this script)
 # TODO: provide an optional option to automatically create google domain verification TXT record through API (need Google business account at console) - Google site verification
 # TODO: create hostname and setup dkim, dmarc, at linode spf at linode (use common subdomain, ftp, mail, www, smtp, pop) - normally it should be created first before installing DA but dkim need to be updated.
-# This function will be used to automatically unlock LUKS disk encryption on boot
-# Must pass the port and password
-# Usage: ssh_luks_unlock <port> <password>
-# eg: ssh_luks_unlock 2222 "strong_password"
+
+# This function is used to unlock LUKS disk encryption on boot via terminal
+# Usage: ssh_luks_unlock <drop_bear_port> <disk_luks_password>
+# Note 1: The drop_bear_port is setup using dropbear-initramfs (This is set in OS preseed-file and config file)
+# Note 2: The disk_luks_password is the OS LUKS encryption password (This is set in OS preseed-file and config file)
+# Note 3: The unlock method required a port and a password. It will use a normal SSH with certificate (Certificate is set in OS preseed-file)
+# Note 4: After it has successfully logged into the system via SSH, we write the disk_luks_password using this code and the OS will automatically unlock it: "echo -ne \"${pass}\" > /lib/cryptsetup/passfifo"
+# eg calling within code: ssh_luks_unlock 2222 "1234"
+# eg calling outside code: <script_name> --ssh-luks-unlock 2222 "1234"
 function ssh_luks_unlock() {
   local port pass rsa_private_key
   port="$1"
@@ -40,10 +45,10 @@ function ssh_luks_unlock() {
   fi
 }
 
-# This function will check if defined server and port is available (listening)
+# This function will check if defined server and port is available (in a listening state)
 # Usage: check_server_port <server> <port>
-# eg: check_server_port sun.sofibox.com 22
-# It will return 0 (if available), and other return code (if not available)
+# eg: check_server_port test.sofibox.com 22
+# It will return 0 (if available), and other return codes (if listening state for the port is not available)
 function check_server_port() {
   local server port result
   server="$1"
@@ -54,6 +59,8 @@ function check_server_port() {
 }
 # This function is used to manage SSH key (create, get, copy)
 # Usage: ssh_key_manager create-key|create-key-with-putty <group_name> <user> <comment>
+# Note 1: create-key will create normal ssh key
+# Note 2: create-key-with-putty will create ssh key with putty format
 # eg: ssh_key_manager "create-key-with-putty" "group" "user" "comment"
 # eg: ssh_key_manager "get-public-key" "group" "user"
 # eg: ssh_key_manager "copy-all-pubkeys"
@@ -72,33 +79,52 @@ function ssh_key_manager() {
   rsa_private_key_ppk="${SCRIPT_PATH}/secure/ssh/${group}_${uname}_${BOX_HOSTNAME_FQDN}.ppk"
 
   if [ "${action}" == "create-key" ]; then
+
     comment="$3"
-    ssh-keygen -f "${rsa_private_key}" -t rsa -b 4096 -P "" -C "${comment}" <<<y
+    if [ $# -eq 3 ]; then
+      echo "Creating SSH key ..."
+      ssh-keygen -f "${rsa_private_key}" -t rsa -b 4096 -P "" -C "${comment}" <<<y
+    else
+      echo "Warning, not enough argument to create key!"
+      return 1
+    fi
   elif [ "${action}" == "create-key-with-putty" ]; then
     comment="$3"
-    install_required "putty-tools"
-    ssh-keygen -f "${rsa_private_key}" -t rsa -b 4096 -P "" -C "${comment}" <<<y
-    puttygen "${rsa_private_key}" -o "${rsa_private_key_ppk}"
+    if [ $# -eq 3 ]; then
+      install_required "putty-tools"
+      echo "Creating SSH key ..."
+      ssh-keygen -f "${rsa_private_key}" -t rsa -b 4096 -P "" -C "${comment}" <<<y
+      echo "Creating SSH key for putty ..."
+      puttygen "${rsa_private_key}" -o "${rsa_private_key_ppk}"
+    else
+      echo "Warning, not enough argument to create key!"
+      return 1
+    fi
   elif [ "${action}" == "get-public-key" ]; then
     if [ -f "${rsa_public_key}" ]; then
       cat "${rsa_public_key}"
     else
       _echo 'red' "Warning, public key does not exist. Please create it first"
+      return 1
     fi
     # Warning this will replace existing key
   elif [ "${action}" == "copy-all-pubkeys" ]; then
+    echo "Resetting known_hosts and copying all public key to /root/.ssh/* ..."
     echo >/root/.ssh/known_hosts
     cp "${SCRIPT_PATH}"/secure/ssh/*.id_rsa* /root/.ssh/
     chmod -R 600 /root/.ssh/
+  else
+    _echo 'red' "Warning, unknown action argument specified when calling ssh_key_manager function!"
+    return 1
   fi
 }
 # This function is used to login into server (SSH login)
 # It can be supplied with script and run in silent/noisy mode
 # Usage: ssh_login "<server>:<port>" "<group>:<user>" <silent> optional_script_path>
-# eg: ssh_login sun.sofibox.com:893 root:root silent/noisy /path_to_script
-# eg2: ssh_login sun.sofibox.com:893 root:root /path_to_script
-# eg3: ssh_login sun.sofibox.com:893 root:root
-# eg4: ssh_login sun.sofibox.com:893 root:root "noisy"
+# eg: ssh_login test.sofibox.com:897 root:root silent/noisy /path_to_script
+# eg2: ssh_login test.sofibox.com:897 root:root /path_to_script
+# eg3: ssh_login test.sofibox.com:897 root:root
+# eg4: ssh_login test.sofibox.com:897 root:root "noisy"
 function ssh_login() {
   if [ -z "$1" ]; then
     echo ""
@@ -2203,6 +2229,7 @@ function linode_api_admin() {
     email="$3"
     ${LINODE_CLI_BIN} domains create --type "${type}" --domain "${domain}" --soa_email "${email}" --json --pretty
   #linode_api_admin "add-dns-record" "maxibi.com" "TXT" "x._domainkey" "*i..2uiu1KJM@#9IU@J()!@IJI92" "5"
+  # For mx record, linode_api_admin "add-dns-record" "maxibi.com" "MX" "mail" "sofibox.com." "5"
   elif [[ "${action}" == "add-dns-record" ]]; then
     shift
     local domain name ttl type value domain_id dis_args retval add_dns_record
@@ -2225,10 +2252,18 @@ function linode_api_admin() {
         # Here is the real result for domain ID:
         # echo "${domain_id}"
         echo "[${SCRIPT_NAME}]: Adding new DNS record name ${name} in linode ..." 2>&1 | tee -a "${REPORT_FILE}"
-
-        add_dns_record=$(${LINODE_CLI_BIN} domains records-create "${domain_id}" --pretty --json \
-          --type "${type}" --name "${name}" --target "${value}" --ttl_sec "${ttl}")
-        retval=$?
+        # MX record got extra priority
+        if [ "${type}" == "MX" ]; then
+          # TODO make sure priority can be passed via argument (currently set to 10 by default for MX record)
+          #linode-cli domains records-create ${sofibox_id} --type MX --name mail --target sofibox.com. --priority 10 --ttl_sec 1
+          add_dns_record=$(${LINODE_CLI_BIN} domains records-create "${domain_id}" --pretty --json \
+            --type "${type}" --name "${name}" --target "${value}" --priority 10 --ttl_sec "${ttl}")
+          retval=$?
+        else
+          add_dns_record=$(${LINODE_CLI_BIN} domains records-create "${domain_id}" --pretty --json \
+            --type "${type}" --name "${name}" --target "${value}" --ttl_sec "${ttl}")
+          retval=$?
+        fi
         if [ ${retval} = 0 ]; then
           echo "=~=~=~=~=~=~=~=~=~=~=" 2>&1 | tee -a "${REPORT_FILE}"
           echo "Success, record has been successfully added into linode DNS management" 2>&1 | tee -a "${REPORT_FILE}"
@@ -4963,9 +4998,9 @@ configure_csf() {
         sleep 1
         # This also must have comma,
         if [ -n "${CSF_EXTRA_ALLOW_PORTS}" ]; then
-        all_allow_ports=",${DA_PORT},${CSF_EXTRA_ALLOW_PORTS}"
+          all_allow_ports=",${DA_PORT},${CSF_EXTRA_ALLOW_PORTS}"
         else
-        all_allow_ports=",${DA_PORT}"
+          all_allow_ports=",${DA_PORT}"
         fi
         echo "DEBUG: all_allow_ports=${all_allow_ports}"
         grep -wq "^TCP_IN = .*${all_allow_ports}" /etc/csf/csf.conf
@@ -7413,7 +7448,7 @@ configure_da_dns_templates() {
     ipv6_full_uncompressed=$(ipv6calc --addr2fulluncompaddr "${IPV6_ADD0}")
     echo "[${SCRIPT_NAME}]: Setting extra_spf_value with ipv6:${ipv6_full_uncompressed} ..." 2>&1 | tee -a "${REPORT_FILE}"
     sleep 1
-    ${da_bin} set extra_spf_value " ipv6:${ipv6_full_uncompressed}" 2>&1 | tee -a "${REPORT_FILE}"
+    ${da_bin} set extra_spf_value " ip6:${ipv6_full_uncompressed}" 2>&1 | tee -a "${REPORT_FILE}"
     restart_da
     # rewrite_confs here so that dns_txt.conf is updated
     # Fixed DNS new record updated:
@@ -7885,6 +7920,14 @@ function configure_da_reseller_accounts() {
           echo "" 2>&1 | tee -a "${REPORT_FILE}"
           echo "" 2>&1 | tee -a "${REPORT_FILE}"
 
+          # For mx record, linode_api_admin "add-dns-record" "maxibi.com" "MX" "mail" "sofibox.com." "5"
+          echo "[${SCRIPT_NAME}]: Creating MX record for ${da_reseller_domain_first} in linode DNS management ..."
+          echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+          linode_api_admin "add-dns-record" "${da_reseller_domain_first}" "MX" "mail" "${da_reseller_domain_first}." "5"
+          echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+          echo "" 2>&1 | tee -a "${REPORT_FILE}"
+          echo "" 2>&1 | tee -a "${REPORT_FILE}"
+
           echo "[${SCRIPT_NAME}]: Deleting external DNS record on linode for domain ${da_reseller_domain_first} ... "
           echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
           echo "[linode delete-dns-record]: Name: _domainkey | Type: TXT" 2>&1 | tee -a "${REPORT_FILE}"
@@ -8021,6 +8064,14 @@ function configure_da_reseller_accounts() {
               echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
 
               linode_api_admin "create-domain" "master" "${extra_domain}" "${this_da_reseller_system_email}"
+              echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+              echo "" 2>&1 | tee -a "${REPORT_FILE}"
+              echo "" 2>&1 | tee -a "${REPORT_FILE}"
+
+              # For mx record, linode_api_admin "add-dns-record" "maxibi.com" "MX" "mail" "sofibox.com." "5"
+              echo "[${SCRIPT_NAME}]: Creating MX record for ${extra_domain} in linode DNS management ..."
+              echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+              linode_api_admin "add-dns-record" "${extra_domain}" "MX" "mail" "${extra_domain}." "5"
               echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
               echo "" 2>&1 | tee -a "${REPORT_FILE}"
               echo "" 2>&1 | tee -a "${REPORT_FILE}"
@@ -8467,6 +8518,15 @@ function configure_da_user_accounts() {
           echo "0) Name: _domainkey | Type: TXT" 2>&1 | tee -a "${REPORT_FILE}"
           #_pause 2
           echo "-----" 2>&1 | tee -a "${REPORT_FILE}"
+
+          # For mx record, linode_api_admin "add-dns-record" "maxibi.com" "MX" "mail" "sofibox.com." "5"
+          echo "[${SCRIPT_NAME}]: Creating MX record for ${da_user_domain_first} in linode DNS management ..."
+          echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+          linode_api_admin "add-dns-record" "${da_user_domain_first}" "MX" "mail" "${da_user_domain_first}." "5"
+          echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+          echo "" 2>&1 | tee -a "${REPORT_FILE}"
+          echo "" 2>&1 | tee -a "${REPORT_FILE}"
+
           linode_api_admin "delete-dns-record" "${da_user_domain_first}" "_domainkey" "TXT"
 
           echo "Deleting dns record x._domainkey for ${da_user_domain_first}" 2>&1 | tee -a "${REPORT_FILE}"
@@ -8585,6 +8645,14 @@ function configure_da_user_accounts() {
               echo "[${SCRIPT_NAME}]: DNS provider is set to linode. Using linode API" 2>&1 | tee -a "${REPORT_FILE}"
               echo "[${SCRIPT_NAME}]: Creating domain ${extra_domain} if missing ..."
               linode_api_admin "create-domain" "master" "${extra_domain}" "${this_da_user_system_email}"
+
+              # For mx record, linode_api_admin "add-dns-record" "maxibi.com" "MX" "mail" "sofibox.com." "5"
+              echo "[${SCRIPT_NAME}]: Creating MX record for ${extra_domain} in linode DNS management ..."
+              echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+              linode_api_admin "add-dns-record" "${extra_domain}" "MX" "mail" "${extra_domain}." "5"
+              echo "~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+              echo "" 2>&1 | tee -a "${REPORT_FILE}"
+              echo "" 2>&1 | tee -a "${REPORT_FILE}"
 
               echo "0) Name: _domainkey | Type: TXT" 2>&1 | tee -a "${REPORT_FILE}"
               #_pause 2
@@ -10298,10 +10366,10 @@ function post_setup() {
   if [ ! -f "${CONF_PATH}/${FUNCNAME[0]}_executed" ]; then
     echo "[${SCRIPT_NAME}]: Executing ${FUNCNAME[0]} ..." 2>&1 | tee -a "${REPORT_FILE}"
     if [ "${DISTRO_ID}" == "debian" ]; then
-    # Install speedtest-cli
-    curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
-    apt-get install speedtest
-    apt-get -y install ncdu htop mailutils gpg vim 2>&1 | tee -a "${REPORT_FILE}"
+      # Install speedtest-cli
+      curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
+      apt-get install speedtest
+      apt-get -y install ncdu htop mailutils gpg vim mutt 2>&1 | tee -a "${REPORT_FILE}"
     else
       echo "Warning, check the post_setup installation for ${DISTRO_ID}, it's only available for debian!"
     fi
@@ -11032,7 +11100,6 @@ ENDSSH
     ;;
 
   # This will generate a modified operating system ISO file that can be used to automatically install OS when booting.
-
   -ci | --create-iso | --build-iso | --preseediso)
     shift
     create_os_iso "$@"
@@ -11061,8 +11128,8 @@ ENDSSH
     ;;
   -t | --test)
     shift
-   # ssh_transfer "${BOX_HOSTNAME_FQDN}:${SSH_PORT}" "root:${ROOT_USERNAME}" "maxisetup maxisetup.conf" ~/
- ssh_login "${BOX_HOSTNAME_FQDN}:${SSH_PORT}" "root:${ROOT_USERNAME}" "${SCRIPT_PATH}/maxisetup_ssh.sh"
+    # ssh_transfer "${BOX_HOSTNAME_FQDN}:${SSH_PORT}" "root:${ROOT_USERNAME}" "maxisetup maxisetup.conf" ~/
+    ssh_login "${BOX_HOSTNAME_FQDN}:${SSH_PORT}" "root:${ROOT_USERNAME}" "${SCRIPT_PATH}/maxisetup_ssh.sh"
     #ssh_login "sun.sofibox.com":"893" "rescue:root"
     #ssh_key_manager "create-key" "admin" "test1" "comment1"
     #ssh_key_manager "get-public-key" "admin" "test1"
