=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~+~=~=~= - Fixed expect package got install and remove in loop
- Added new API for requesting SSL certificate with different providers (fully support letsencrypt)

- Added new function configure_da_domain_ssl

- Call linode API to delete existing and add fresh DNS record created Directly from Directadmin local/internal DNS

- New variable in maxisetup.config called DA_USER_SSL_SUB_NAME[index]

SYNTAX for this variable:

DA_USER_SSL_SUB_NAME[index]=("<ssl_provider>:<root_domain>:<subdomain1.subdomain2+subdomain2.subdomain3+subdomainN>" "...")"

---

Full example how to create user da_user:

DA_USER_USERNAME1="da_user"
DA_USER_USERPASS1="*long-secured-password*"
DA_USER_SYSTEM_EMAIL1="webmaster@maxibi.com"
DA_USER_MAIL_USER1=("email1@maxibi.com" "email2@maxibi.com")
DA_USER_MAIL_PASSWORD1=("*mailpassword1" "*mailpassword2")
DA_USER_DOMAIN1=("maxibi.com" "maxi32.com")
DA_USER_SUBDOMAIN1=("sales+maxibi.com" "login+maxibi.com" "sub1.sub2+maxibi.com" subextra+maxi32.com)
DA_USER_PACKAGE_NAME1="USER_UNLIMITED"
DA_USER_DOMAIN_ENABLE_SSL1="yes"
# Define SSL provider for each domain here
# <ssl_provider>:<root_domain>:subdomain1.subdomain2+subdomain2.subdomain3+subdomainx
# ssl_provider such as letsencrypt, digicert etc:
# The root domain should be ssl-ed by default
DA_USER_SSL_SUB_NAME1=("letsencrypt:maxibi.com:www+ftp+mail+pop+smtp+sales" digicert:maxi32:www+shop)

==============

The above config will do the following:

1) Create a Directadmin user called 'da_user' with a given strong password and it also has a system email assigned as webmaster@maxibi.com
2) This da_user also will have 2 working email accounts both called email1@maxibi.com and email2@maxibi.com (you can add more emails)
3) This da_user will have 2 domains called maxibi.com and maxi32.com (you can add more domains)
4) This da_user will have subdomains called sales, login and sub1.sub2 for the domain under maxibi.com and another subdomain call subextra under the domain maxi32.com (You can create more subdomain as it supports multi subdomains as well such as sub1.sub2.sub3.sub4.domain.com)
5) This da_user will have a web hosting package assigned as USER_UNLIMITED (must be created previously by a Reseller for this user. The script will check if it doesn't exist)
6) Letsencrypt will automatically request certificate for the domain maxibi.com including the extra subdomain www,ftp,mail,pop,smtp,sales AND digicert will automatically request certificate for the domain maxi32 including extra subdomain www and shop (digicert is on TODO list: currently if you use digicert you will get a message "Error, this provider digicert has no API yet). You can define which subdomains or domains should have SSL certificate easily with this method.

=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~+~=~=~=

diff --git a/maxisetup b/maxisetup
--- a/maxisetup
+++ b/maxisetup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 # Author: Arafat Ali Email: arafat@sofibox.com
-# Version 0.3.7.1-beta
+# Version 0.3.7.2-beta
 # This is an initial server hardening script for CentOS and Debian.
 # Compatible 100% with Directadmin. Supported OS: CentOS + Debian (Planned on FreeBSD)
 # You can choose to install as the other stack server such as LEMP, Laravel etc defined in config file (TODO)
@@ -163,9 +163,9 @@ function linode_api_admin() {
               ")
     echo "Result: "
     echo "${LINODE_CLI}"
+    # Remove expect
+    apt-get -y remove expect
   fi
-  # Remove expect
-  apt-get -y remove expect
 
   if ! command -v jq &>/dev/null; then
     echo "[${SCRIPT_NAME}]: Warning, missing jq component. This utility requires jq to be installed." 2>&1 | tee -a "${REPORT_FILE}"
@@ -771,6 +771,28 @@ function da_api_admin() {
       # CMD_API_SUBDOMAIN AND CMD_API_SUBDOMAINS are the same thing: https://www.directadmin.com/features.php?id=1589
       command="CMD_API_SUBDOMAIN"
       data="domain=${root_domain}&subdomain=${sub_domain}&json=yes&action=create"
+      method="POST"
+    # da_api_admin "request-domain-ssl" <provider> <root_domain> <keysize> <encryption> <ssl_sub_domains_query>
+    # da_api_admin "request-domain-ssl" letsencrypt codegix.com secp521r1 sha256 "le_select0=codegix.com&le_select1=www.codegix.com&le_select2=ftp.codegix.com \
+    # &le_select3=mail.codegix.com&le_select4=pop.codegix.com&le_select5=smtp.codegix.com&le_select6=dashboard.codegix.com&le_select7=secure.codegix.com"
+    elif [ "${action}" == "request-domain-ssl" ]; then
+      local ssl_root_domain ssl_key_size ssl_encryption
+      shift
+      ssl_provider="$1"
+      ssl_root_domain="$2"
+      ssl_key_size="$3"
+      ssl_encryption="$4"
+      ssl_sub_domains_query="$5"
+      # CMD_API_SUBDOMAIN AND CMD_API_SUBDOMAINS are the same thing: https://www.directadmin.com/features.php?id=1589
+      command="CMD_API_SSL"
+      if [ "${ssl_provider}" == "letsencrypt" ]; then
+        data="type=create&request=letsencrypt&name=${ssl_root_domain}&keysize=${ssl_key_size}&encryption=${ssl_encryption} \
+      &wildcard=no&domain=${ssl_root_domain}&json=yes&action=save&background=auto&${ssl_sub_domains_query}"
+      else
+        # Give error because we focus on letsencrypt first
+        echo "[${SCRIPT_NAME}]: Error, this provider ${ssl_provider} has no API yet" 2>&1 | tee -a "${REPORT_FILE}"
+        _exit 1
+      fi
       method="POST"
     else
       echo "[${SCRIPT_NAME}]: The API action '${action}' does not exist!" 2>&1 | tee -a "${REPORT_FILE}"
@@ -3909,7 +3931,7 @@ function configure_da_accounts() {
 }
 
 function configure_da_subdomains() {
-  rm -f "${CONF_PATH}/${FUNCNAME[0]}_executed"
+  #rm -f "${CONF_PATH}/${FUNCNAME[0]}_executed"
   if [ ! -f "${CONF_PATH}/${FUNCNAME[0]}_executed" ]; then
     echo "[${SCRIPT_NAME}]: Executing ${FUNCNAME[0]} ..." 2>&1 | tee -a "${REPORT_FILE}"
     local da_user_subdomains da_user_subdomains_count this_da_user_username this_da_user_userpass this_da_user_subdomains
@@ -3971,8 +3993,17 @@ function configure_da_subdomains() {
         # da_api_admin "create-user-subdomain" "<root_domain>" "<subdomain>"
         # Start the user login authentication:
         da_api_admin "start+${this_da_user_username}+${this_da_user_userpass}"
-
         da_api_admin "create-user-subdomain" "${root_domain}" "${sub_domain}"
+
+        # Also add subdomain for linode API here
+
+        #linode_api_admin "delete-dns-record" <domain_name> <record_name> <record_type>
+        linode_api_admin "delete-dns-record" "${root_domain}" "${sub_domain}" "A"
+        linode_api_admin "delete-dns-record" "${root_domain}" "${sub_domain}" "AAAA"
+
+        #linode_api_admin "add-dns-record" "maxibi.com" "TXT" "x._domainkey" "*i..2uiu1KJM@#9IU@J()!@IJI92" "5"
+        linode_api_admin "add-dns-record" "${root_domain}" "A" "${sub_domain}" "${IPV4_ADD0}" "5"
+        linode_api_admin "add-dns-record" "${root_domain}" "AAAA" "${sub_domain}" "${IPV6_ADD}" "5"
 
         ((count_n++))
       done
@@ -4072,12 +4103,86 @@ function configure_da_emails() {
 }
 
 function configure_da_domain_ssl() {
-  :
-  # TODO make sure to check what file is created when requesting certificate on user domain
-  # TODO test this file if it can restore from cloud backup (need maxicloud: TODO)
-
   # Here we configure SSL for specific domains we want based on the config variable: DA_USER_DOMAIN_ENABLE_SSL{?}
   # Where Domain can have 1 or more
+  #rm -f "${CONF_PATH}/${FUNCNAME[0]}_executed"
+  if [ ! -f "${CONF_PATH}/${FUNCNAME[0]}_executed" ]; then
+    echo "[${SCRIPT_NAME}]: Executing ${FUNCNAME[0]} ..." 2>&1 | tee -a "${REPORT_FILE}"
+    # Get all the user ssl_sub_names
+    da_user_ssl_sub_names="${!DA_USER_SSL_SUB_NAME@}"
+    # Get the total count for user ssl_sub_names
+    da_user_ssl_sub_names_count=$(echo "${da_user_ssl_sub_names}" | wc -w)
+
+    count_x=1
+    while [[ ${count_x} -le ${da_user_ssl_sub_names_count} ]]; do
+      echo ""
+      echo ""
+      echo "===== countx = ${count_x} ========="
+      typeset -n "this_da_user_username"="DA_USER_USERNAME${count_x}"
+      typeset -n "this_da_user_userpass"="DA_USER_USERPASS${count_x}"
+      typeset -n "this_da_user_domain_enable_ssl"="DA_USER_DOMAIN_ENABLE_SSL${count_x}"
+      typeset -n "this_da_user_ssl_sub_names"="DA_USER_SSL_SUB_NAME${count_x}"
+
+      echo "this_da_user_username: ${this_da_user_username}"
+      echo "this_da_user_userpass: ${this_da_user_userpass}"
+      echo "this_da_user_domain_enable_ssl: ${this_da_user_domain_enable_ssl}"
+      echo "this_da_user_ssl_sub_names: ${this_da_user_ssl_sub_names[*]}"
+      this_da_user_ssl_sub_names_count=${#this_da_user_ssl_sub_names[@]}
+
+      if [[ ${this_da_user_domain_enable_ssl} == "yes" ]]; then
+        echo ""
+        echo "=========================================="
+        echo "OK, This user is set to enable SSL"
+        count_n=0
+        while [ ${count_n} -le $((this_da_user_ssl_sub_names_count - 1)) ]; do
+          echo ""
+          echo "---count_n=${count_n} ---"
+          ssl_provider=$(echo "${this_da_user_ssl_sub_names[count_n]}" | awk -F':' '{ print $1 }')
+          ssl_domain=$(echo "${this_da_user_ssl_sub_names[count_n]}" | awk -F':' '{ print $2 }')
+          ssl_subdomains_raw=$(echo "${this_da_user_ssl_sub_names[count_n]}" | awk -F':' '{ print $3 }')
+          # Debug
+          echo "SSL_PROVIDER: ${ssl_provider}"
+          echo "SSL_DOMAIN: ${ssl_domain}"
+          echo "SSL_SUBDOMAINS_RAW: ${ssl_subdomains_raw}"
+
+          ssl_subdomains=$(echo "${ssl_subdomains_raw}" | awk -F'+' '{for (i=0;i<=NF;i++)print $i}')
+          count_o=0
+          le_select_query=""
+          for ssl_subdomain in ${ssl_subdomains}; do
+            if [ ${count_o} = 0 ]; then
+              le_select[${count_o}]="${ssl_domain}"
+              ls="le_select${count_o}=${le_select[${count_o}]}"
+            else
+              le_select[${count_o}]="${ssl_subdomain}.${ssl_domain}"
+              ls="&le_select${count_o}=${le_select[${count_o}]}"
+            fi
+            le_select_query="${le_select_query}${ls}"
+            ((count_o++))
+          done
+          echo "---------------"
+          echo "LE_SELECT_QUERY: ${le_select_query}"
+          echo ""
+          # Now we got all variables. Call API here:
+          # da_api_admin "request-domain-ssl" <provider> <root_domain> <keysize> <encryption> <ssl_sub_domains_query>
+          da_api_admin "start+${this_da_user_username}+${this_da_user_userpass}"
+          # Most secure key now is secp521r1 and sha256
+          echo "Requesting SSL for domain ${ssl_domain} with the following query: ${le_select_query}"
+          da_api_admin "request-domain-ssl" "${ssl_provider}" "${ssl_domain}" "secp521r1" "sha256" "${le_select_query}"
+          ((count_n++))
+        done
+
+      elif [[ ${this_da_user_domain_enable_ssl} == "no" ]]; then
+        echo "Warning This user is set to not enable SSL. Do nothing for this"
+      fi
+      echo "=========================================="
+      ((count_x++))
+
+    done
+    check_finish_reboot "${FUNCNAME[0]}"
+  else
+    echo "[${SCRIPT_NAME}]: [Skipped]: ${FUNCNAME[0]} has ran before" 2>&1 | tee -a "${REPORT_FILE}"
+    echo "=~=~=~=~=~=~=~=~=~" 2>&1 | tee -a "${REPORT_FILE}"
+  fi
 }
 
 # This is used to install extra packages like ncdu, htop and more
@@ -4326,7 +4431,7 @@ if [ "${INSTALL_TYPE}" == "DIRECTADMIN" ]; then
   configure_da_subdomains
   #exit 1
   configure_da_emails
-  # exit 1
+  #exit 1
   configure_da_domain_ssl
   #exit 1
   configure_da_memcached
