Update maxida --api to use any users to use that API (before only owner can use) (note maxida is a private repo) Update maxisetup DA API to set DKIM and obtained DKIM value. This value is important to be used by external DNS. For example, we can use linode API to update this DKIM value automatically as external DNS record. Linode API will be coming soon ...

diff --git a/maxisetup b/maxisetup
--- a/maxisetup
+++ b/maxisetup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
 # Author: Arafat Ali Email: arafat@sofibox.com
-# Version 0.3.4.4-beta
+# Version 0.3.4.5-beta
 # This is an initial server hardening script for general server using CentOS and Debian.
 # Compatible 100% with Directadmin. Supported OS: CentOS + Debian (Planned on FreeBSD)
 # Read the code to know what the scripts offer.
@@ -134,13 +134,14 @@ function restart_da() {
 function da_api_admin() {
   # By default, da_api_admin will use owner authentication if I don't supply this: da_api_admin "end+owner"
   local api_username api_password
-  local command data method input decoded_status
+  local command data method input decoded_status filter_cmd
   local action username email password
   local owner_main_auth owner_new_list admin_new_list admin_list reseller_new_list admin_ori_list admin_main_auth
   local reseller_main_auth user_main_auth user_new_list
   local ip netmask ssl
   local domain ip_type
   local package_name
+  local role_user
   admin_list="/usr/local/directadmin/data/admin/admin.list"
   admin_new_list=$(grep -w "${DA_ADMIN_USERNAME1}" "${admin_list}")
   owner_new_list=$(grep -w "${DA_OWNER_USERNAME1}" "${admin_list}")
@@ -392,17 +393,46 @@ function da_api_admin() {
       command="CMD_API_DOMAIN"
       data="domain=${domain}&uquota=unlimited&ssl=ON&php=ON&json=yes&action=create&ubandwidth=unlimited"
       method="POST"
+    elif [ "${action}" == "enable-email-dkim" ]; then
+      shift
+      domain="$1"
+      command="CMD_API_EMAIL_POP"
+      data="action=set_dkim&domain=${domain}&json=yes&enable=yes"
+      method="POST"
+
+    elif [ "${action}" == "get-dns-zone" ]; then
+      # da_api_admin "get-dns-zone" "maxibi.com"
+      shift
+      domain="$1"
+      filter_cmd="$2"
+      command="CMD_API_DNS_CONTROL"
+      data="domain=${domain}"
+      method="POST"
     else
       echo "[${SCRIPT_NAME}]: The API action '${action}' does not exist!"
       exit 1
     fi
     # Executing API via curl based on command above
-    input=$(curl --request "${method}" --user "${api_username}":"${api_password}" --data "${data}" "${ssl}://${BOX_HOSTNAME_FQDN}:${DA_PORT}/${command}")
-    decoded_status=$(printf '%b' "${input//%/\\x}")
-    echo "---" 2>&1 | tee -a "${REPORT_FILE}"
-    echo "[${SCRIPT_NAME}]: Status: ${decoded_status} | status=0 means success" 2>&1 | tee -a "${REPORT_FILE}"
-    #exit 1
-    echo "" 2>&1 | tee -a "${REPORT_FILE}"
+    if [ "${filter_cmd}" == "x._domainkey+VALUE" ]; then
+      # Here we just display that single value for this filtering
+      curl --request "${method}" --user "${api_username}":"${api_password}" --data "${data}" "${ssl}://${BOX_HOSTNAME_FQDN}:${DA_PORT}/${command}" | grep 'x._domainkey' | awk '{ print $6" "$7" "$8}'
+      # get out based on return value
+      return $?
+    elif [ "${filter_cmd}" == "x._domainkey+TTL" ]; then
+      curl --request "${method}" --user "${api_username}":"${api_password}" --data "${data}" "${ssl}://${BOX_HOSTNAME_FQDN}:${DA_PORT}/${command}" | grep 'x._domainkey' | awk '{ print $2}'
+      # get out based on return value
+      return $?
+    elif [ "${filter_cmd}" == "x._domainkey+TYPE" ]; then
+      curl --request "${method}" --user "${api_username}":"${api_password}" --data "${data}" "${ssl}://${BOX_HOSTNAME_FQDN}:${DA_PORT}/${command}" | grep 'x._domainkey' | awk '{ print $4}'
+      # get out based on return value
+      return $?
+    else
+      input=$(curl --request "${method}" --user "${api_username}":"${api_password}" --data "${data}" "${ssl}://${BOX_HOSTNAME_FQDN}:${DA_PORT}/${command}")
+      decoded_status=$(printf '%b' "${input//%/\\x}")
+      echo "---" 2>&1 | tee -a "${REPORT_FILE}"
+      echo "[${SCRIPT_NAME}]: Status: ${decoded_status} | status=0 means success" 2>&1 | tee -a "${REPORT_FILE}"
+      echo "" 2>&1 | tee -a "${REPORT_FILE}"
+    fi
   else
     echo "[${SCRIPT_NAME}]: Argument given is: $1" 2>&1 | tee -a "${REPORT_FILE}"
   fi
@@ -2652,8 +2682,9 @@ function configure_maxida() {
       # Here we create environment variables to use maxida API (Directadmin API). Very important to supply initial authentication
       echo "[${SCRIPT_NAME}]: Creating environment variable for maxida at ${maxida_env} ..." 2>&1 | tee -a "${REPORT_FILE}"
       sleep 1
-      sed -i "s/^DA_OWNER_USERNAME1=.*/DA_OWNER_USERNAME1=\"${DA_OWNER_USERNAME1}\"/" ${maxida_env}
-      sed -i "s/^DA_OWNER_USERPASS1=.*/DA_OWNER_USERPASS1=\"${DA_OWNER_USERPASS1}\"/" ${maxida_env}
+      # Put admin authentication:
+      sed -i "s/^API_USERNAME=.*/API_USERNAME=\"${DA_OWNER_USERNAME1}\"/" ${maxida_env}
+      sed -i "s/^API_USERPASS=.*/API_USERPASS=\"${DA_OWNER_USERPASS1}\"/" ${maxida_env}
       sed -i "s/^BOX_HOSTNAME_FQDN=.*/BOX_HOSTNAME_FQDN=\"${BOX_HOSTNAME_FQDN}\"/" ${maxida_env}
       sed -i "s/^DA_PORT=.*/DA_PORT=\"${DA_PORT}\"/" ${maxida_env}
     else
@@ -3108,6 +3139,7 @@ function configure_da_accounts() {
     local da_user_unames #da_user_passwords da_user_emails da_user_domains da_user_package_names
     local this_da_user_uname this_da_user_password this_da_user_email this_da_user_domain this_da_user_package_name
     local da_user_count domains
+    local dkim_val
     da_admin_packages_list="/usr/local/directadmin/data/admin/packages.list"
     da_user_packages_list="/usr/local/directadmin/data/users/${DA_RESELLER_USERNAME1}/packages.list"
     # ALL API documentation: https://www.directadmin.com/search_versions.php?query=CMD_API
@@ -3184,10 +3216,18 @@ function configure_da_accounts() {
           echo "[${SCRIPT_NAME}]: [${SCRIPT_NAME}]: Found package ${this_da_user_package_name}. Creating user account using package name ${this_da_user_package_name} ..." 2>&1 | tee -a "${REPORT_FILE}"
           da_user_domain_count=$(echo "${this_da_user_domain}" | wc -w)
           da_user_domain_first=$(echo "${this_da_user_domain}" | awk '{ print $1 }')
+          da_api_admin "start+reseller"
           da_api_admin "create-user-account" "${this_da_user_uname}" "${this_da_user_email}" "${this_da_user_password}" "${da_user_domain_first}" "${this_da_user_package_name}"
+          echo "[${SCRIPT_NAME}]: Enabling email DKIM for domain ${da_user_domain_first} ..." 2>&1 | tee -a "${REPORT_FILE}"
+          _pause 2
+          da_api_admin "start+${this_da_user_uname}+${this_da_user_password}"
+          da_api_admin "enable-email-dkim" "${da_user_domain_first}"
+          dkim_val=$(da_api_admin "get-dns-zone" "${this_da_user_domain}" "x._domainkey+VALUE" | tail -n 1)
+          echo "The dkim value for this domain ${da_user_domain_first} is: ${dkim_val}"
+
           if [ "${da_user_domain_count}" -gt 1 ]; then
             echo "[${SCRIPT_NAME}]: This user ${this_da_user_uname} has ${da_user_domain_count} domains" 2>&1 | tee -a "${REPORT_FILE}"
-            _pause 5
+            _pause 2
             domains=${this_da_user_domain}
             echo ""
             for domain in ${domains}; do
@@ -3195,14 +3235,17 @@ function configure_da_accounts() {
               if [ "${domain}" == "${da_user_domain_first}" ]; then
                 continue
               fi
-              da_api_admin "start+${this_da_user_uname}+${this_da_user_password}"
               echo "[${SCRIPT_NAME}]: Creating extra domain ${domain} for ${this_da_user_uname} ..." 2>&1 | tee -a "${REPORT_FILE}"
-              _pause 5
+              _pause 2
               da_api_admin "create-user-domain" "${domain}"
+              echo "[${SCRIPT_NAME}]: Enabling email DKIM for domain ${domain} ..." 2>&1 | tee -a "${REPORT_FILE}"
+              _pause 2
+              da_api_admin "enable-email-dkim" "${domain}"
+              dkim_val=$(da_api_admin "get-dns-zone" "${domain}" "x._domainkey+VALUE" | tail -n 1)
+              echo "The dkim value for this domain ${domain} is: ${dkim_val}"
             done
           fi
         else
-
           echo "[${SCRIPT_NAME}]: Warning, ${this_da_user_package_name} does not exist in ${da_user_packages_list}. Please inspect why!" 2>&1 | tee -a "${REPORT_FILE}"
           _exit 1
         fi
